/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chai.glb --transform 
Files: chai.glb [2.96MB] > C:\react\chai\chai-app\chai-transformed.glb [231.31KB] (92%)
Author: bhagathgoud (https://sketchfab.com/bhagathgoud)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indian-tea-glass-chai-bc87e1579d544bbd9f7d132095e40e3d
Title: Indian Tea Glass ( Chai )
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../chai-transformed.glb')
  return (
    <group {...props} dispose={null}>
      {/* <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} scale={0.754} /> */}
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} position={[0, 0.02, 0]} scale={0.396} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Glass} position={[0, 0.04, 0]} scale={0.396} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Condensation} position={[0, 0.04, 0]} scale={0.396} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Liquid} position={[0, 0.037, 0]} scale={0.396} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Liquid} position={[-0.17, 0.04, 0]} scale={0.396} />
    </group>
  )
}

useGLTF.preload('/chai-transformed.glb')
